constraintNames = [ 'cPVEnergyBalance',
                    'cPVCapacityLimit',
                    'cStorSoCBalance',
                    'cStorChargeLimit_UB',
                    'cStorLimitDischarge_UB', 
                    'cStorCapacity',
                    'cStorDuration_UB', 
                    'cDCPowrBlockBalance', 
                    'cElyEnergyBalance',
                    'cElyCapacityLimit',
                    'cInvEnergyBalance', 
                    'cInvCapacityLimit', 
                    'cCompCapacityLimit',
                    'cCompPowrReq', 
                    'cH2StorBalance',
                    'cH2StorCapacityLimit', 
                    'cTotalPlantH2Balance', 
                    'cProductionCommitment_LB',
                    'cProductionCommitment Contiguity',
                    'cH2PlantOutput_LB', 
                    'cH2PlantOutput_UB']


parameterDict2020AG = [

    {'idx': 8001, 
    'year': 2020, 
    'storage_type': 'above', 
    'category': 'general', 
    'param_name': 'pCCF', 
    'value': 0.07873476636464005, 
    'units': 'unitless',
    'description': 'Capital charge factor to annualize investment costs.',
    'comments': 'Calculated field using the discount rate (5.4 %) and lifetime value (20 years).'},

    {'idx': 8002, 
    'year': 2020, 
    'storage_type': 'above', 
    'category': 'hydrogen_production', 
    'param_name': 'pH2DesignFlowRate', 
    'value': 4166.667,
    'units': 'kg/hr', 
    'description': 'Designed plant flow rate of hydrogen.',
    'comments': 'Assumption, fixed a priori'},
    
    {'idx': 8003, 
    'year': 2020, 
    'storage_type': 'above', 
    'category': 'hydrogen_production', 
    'param_name': 'pCFPlantLB', 
    'value': 0.9,
    'units': 'unitless', 
    'description': 'Lower bound on plant activity.',
    'comments': 'Lower bound on plant activity, fixed a priori.'},

    {'idx': 8004, 
    'year': 2020, 
    'storage_type': 'above', 
    'category': 'hydrogen_production', 
    'param_name': 'pH2LHV', 
    'value': 120.1, 
    'units': 'MJ/kg',
    'description': 'Lower heating value of hydrogen.',
    'comments': 'Assumption, fixed a priori'},

    {'idx': 8005, 
    'year': 2020, 
    'storage_type': 
    'above', 'category': 'hydrogen_production', 
    'param_name': 'pProductionSlackCost', 
    'value': 0,
    'units': '$/kg', 
    'description': 'Production slack.',
    'comments': 'Initially fixed at zero before model runs.'},

    {'idx': 8006, 
    'year': 2020, 
    'storage_type': 'above', 
    'category': 'pv', 
    'param_name': 'pCapCostPV', 
    'value': 850.0,
    'units': '$/KW', 
    'description': 'Unitized capital cost of PV system.',
    'comments': 'NREL Q1 2018 benchmark $/kWdc https://www.nrel.gov/docs/fy19osti/72399.pdf'},

    {'idx': 8007, 
    'year': 2020, 
    'storage_type': 'above', 
    'category': 'pv', 
    'param_name': 'pFOMCostPV', 
    'value': 8500.0, 
    'units': '$/MW', 
    'description': 'Fixed operating cost of PV system.',
    'comments': 'Assumed to be 1% of CAPEX `pCapCostPV` and converted to $/MW.'},

    {'idx': 8008, 
    'year': 2020, 
    'storage_type': 'above', 
    'category': 'pv', 
    'param_name': 'pVOMCostPV', 
    'value': 0.0,
    'units': '$/MW-hr',  
    'description': 'Variable operating cost of PV system.',
    'comments': 'Assumption, fixed a priori'},

    {'idx': 8009, 
    'year': 2020, 
    'storage_type': 'above', 
    'category': 'pv', 
    'param_name': 'pPVCapFactor', 
    'value': None, 
    'units': 'tbd', 
    'description': 'Hourly PV capacity factor for a given site.',
    'comments': 'From external data source (NREL, TMY), for each site in the model.'},

    {'idx': 8010, 
    'year': 2020, 
    'storage_type': 'above', 
    'category': 'pv', 
    'param_name': 'pGridElecPrice', 
    'value': 120.0, 
    'units': '$/MW-hr',
    'description': 'Hourly wholesale price of electricity from the grid.',
    'comments': 'Fixed, a priori'},

    {'idx': 8011, 
    'year': 2020, 
    'storage_type': 'above', 
    'category': 'inverter', 
    'param_name': 'pCapCostInv', 
    'value': 60.0, 
    'units': '$/MW', 
    'description': 'Inverter capital cost.',
    'comments': 'Assumption made by Mallagragada et al.'},

    {'idx': 8012, 
    'year': 2020, 
    'storage_type': 'above', 
    'category': 'inverter', 
    'param_name': 'pInvEff', 
    'value': 0.96, 
    'units': 'unitless', 
    'description': 'Efficiency of inverter.',
    'comments': 'Assumption, fixed a priori'},

    {'idx': 8013, 
    'year': 2020, 
    'storage_type': 'above', 
    'category': 'battery_storage', 
    'param_name': 'pStEffChg', 
    'value': 0.96, 
    'units': 'unitless', 
    'description': 'Charge efficiency of the battery storage device.',
    'comments': 'Assumption, fixed a priori'},

    {'idx': 8014, 
    'year': 2020, 
    'storage_type': 'above', 
    'category': 'battery_storage', 
    'param_name': 'pStEffDischg',  
    'value': 0.96, 
    'units': 'unitless', 
    'description': 'Discharge efficiency of the battery storage device',
    'comments': 'Assumption, fixed a priori'},

    {'idx': 8015, 
    'year': 2020, 
    'storage_type': 'above', 
    'category': 'battery_storage', 
    'param_name': 'pCapCostPowSt', 
    'value': 589.0, 
    'units': '$/KW', 
    'description': 'Capital cost of the battery storage system.',
    'comments': 'Assumption, fixed a priori (TODO: Get full reference from ref. 13 in the paper.)'},

    {'idx': 8016, 
    'year': 2020, 
    'storage_type': 'above', 
    'category': 'battery_storage', 
    'param_name': 'pCapCostEnergySt', 
    'value': 206.0, 
    'units': '$/KW-hr', 
    'description': 'Capital costs of the battery storage system.',
    'comments': 'Assumption, fixed a priori (TODO: Get full reference from ref. 13 in the paper.)'},

    {'idx': 8017, 
    'year': 2020, 
    'storage_type': 'above', 
    'category': 'battery_storage', 
    'param_name': 'pFOMCostSt', 
    'value': 7873.0, 
    'units': '$/MW-yr', 
    'description': 'Fixed operating cost of the battery storage system.',
    'comments': 'NREL ATB 2018 2020 costs (TODO: get full reference).'},

    {'idx': 8018, 
    'year': 2020, 
    'storage_type': 'above', 
    'category': 'battery_storage', 
    'param_name': 'pVOMCostSt', 
    'value': 2.7, 
    'units': '$/MW-hr', 
    'description': 'Variable operating cost of the battery storage system.',
    'comments': 'Assumption, fixed a priori'},

    {'idx': 8019, 
    'year': 2020, 
    'storage_type': 'above', 
    'category': 'battery_storage', 
    'param_name': 'pDur_UB', 
    'value': 100.0, 
    'units': 'hr', 
    'description': 'Storage duration of the battery storage system.',
    'comments': 'Assumption, fixed a priori'},
    
    {'idx': 8020, 
    'year': 2020, 
    'storage_type': 'above', 
    'category': 'electrolyzer', 
    'param_name': 'pElySpecPower',  
    'value': 57.51915709, 
    'units': 'KW-hr/kg', 
    'description': 'Hydrogen production factor for the electrolyzer system.',
    'comments': 'Median value for electrolyzer efficiency from IEA Future of Hydrogen report, 2019 (=1/0.58*120.1/3.6)'},
    
    {'idx': 8021, 
    'year': 2020, 
    'storage_type': 'above', 
    'category': 'electrolyzer', 
    'param_name': 'pCapCostEly', 
    'value': 800.0, 
    'units': '$/KW', 
    'description': 'Capital cost of the electrolyzer.',
    'comments': 'Value is from Table 2 in `https://www.nrel.gov/docs/fy16osti/65856.pdf`'},
    
    {'idx': 8022, 
    'year': 2020, 
    'storage_type': 'above', 
    'category': 'electrolyzer', 
    'param_name': 'pVOMCostEly', 
    'value': 0.00, 
    'description': 'Variable operating costs for the electrolyzer.',
    'comments': 'Assumption, fixed a priori'},
    
    {'idx': 8023, 
    'year': 2020, 
    'storage_type': 'above', 
    'category': 'electrolyzer', 
    'param_name': 'pFOMCostEly', 
    'value': 56000.0, 
    'units': '$/MW-yr', 
    'description': 'Fixed operating costs for the electrolyzer,',
    'comments': 'Assumed to be 7% of CAPEX `pCapCostEly` and converted to $/MW.'},
    
    {'idx': 8024, 
    'year': 2020, 
    'storage_type': 'above', 
    'category': 'electrolyzer', 
    'param_name': 'pFeedH2OCostEly', 
    'value': 0.014867499, 
    'units': '$/kg', 
    'description': 'Unitized cost for feedwater to produce hydrogen.',
    'comments': 'Value is from Table 10 in `https://www.nrel.gov/docs/fy17osti/67384.pdf` (=0.002375*(2.36+3.9). Units are in terms of kg H2 produced.'},
    
    {'idx': 8025, 
    'year': 2020, 
    'storage_type': 'above', 
    'category': 'hydrogen_storage_compressor', 
    'param_name': 'pCapCostH2Comp', 
    'value': 1200.0, 
    'units': '$/KW', 
    'description': 'Capital cost for the storage compressor.',
    'comments': 'Comes from `CapCostComp_dkW` (TODO: Verify Parks et al. ref 61).'},
    
    {'idx': 8026, 
    'year': 2020, 
    'storage_type': 'above', 
    'category': 'hydrogen_storage_compressor', 
    'param_name': 'pFOMCostH2Comp', 
    'value': 48000.0, 
    'units': '$/MW', 
    'description': 'Fixed operating cost for the storage compressor.',
    'comments': 'Assumed to be 4% of CAPEX `pCapCostH2Comp` and converted to $/MW.'},
    
    {'idx': 8027, 
    'year': 2020, 
    'storage_type': 'above', 
    'category': 'hydrogen_storage_compressor', 
    'param_name': 'pCompSpecPower', 
    'value': 1.0, 
    'units': 'KW-hr/kg', 
    'description': 'Compressor production factor.',
    'comments': 'Assumption made by Mallagragada et al. based on a book (TODO: get full reference).'},
    
    {'idx': 8028, 
    'year': 2020, 
    'storage_type': 'above', 
    'category': 'hydrogen_storage_compressor', 
    'param_name': 'pCapCostH2st', 
    'value': 516.0, 
    'units': '$/kg', 
    'description': 'Capitial costs for the storage compressor.',
    'comments': 'Fixed a priori from Ahluwalia et al. (TODO: get full reference).'},
    
    {'idx': 8029, 
    'year': 2020, 
    'storage_type': 'above', 
    'category': 'hydrogen_storage_compressor', 
    'param_name': 'pFOMCostH2st', 
    'units': '$/kg', 
    'description': 'Fixed operating costs for the storage compressor.',
    'value': 5.16, 'comments': 'Assumed to be 1% from CAPEX `pCapCostH2st` (Penev et al, ref 62).'},
    
    {'idx': 8030, 
    'year': 2020, 
    'storage_type': 'above', 
    'category': 'hydrogen_storage_compressor', 
    'param_name': 'pH2kgpertank', 
    'value': 1000.0, 
    'units': 'kg/unit', 
    'description': 'Capacity of a single hydrogen storage tank.',
    'comments': 'Assumption, fixed a priori. Units are assumed to be in terms of units of H2 storage devices.'}

]

decisionVariables = [

    {'idx': 9001, 
    'year': 2020, 
    'storage_type': 'above', 
    'category': 'pv', 
    'var_name': 'vPVInstalledMW', 
    'time_var': FALSE, 
    'tech_var': FALSE, 
    'type': 'non-negative reals', 
    'note': 'Implicitly, the model assumes that the unit is installed and operates for one year.', 
    'units': 'MW'},

    {'idx': 9002, 
    'year': 2020, 
    'storage_type': 'above', 
    'category': 'pv', 
    'var_name': 'vPVtoDCPow', 
    'time_var': TRUE, 
    'tech_var': FALSE, 
    'type': 'non-negative reals', 
    'note': 'none'},

    {'idx': 9003, 
    'year': 2020, 
    'storage_type': 'above', 
    'category': 'pv', 
    'var_name': 'vPVOutput', 
    'time_var': TRUE, 
    'tech_var': FALSE, 
    'type': 'non-negative reals', 
    'note': 'none'},
    
    {'idx': 9004, 
    'year': 2020, 
    'storage_type': 'above', 
    'category': 'inverter', 
    'var_name': 'vInvInstalledMW', 
    'time_var': FALSE, 
    'tech_var': FALSE, 
    'type': 'non-negative reals', 
    'note': 'Implicitly, the model assumes that the unit is installed and operates for one year.', 
    'units': 'MW'},
    
    {'idx': 9005, 
    'year': 2020, 
    'storage_type': 'above', 
    'category': 'battery_storage', 
    'var_name': 'vStDischarge', 
    'time_var': TRUE, 
    'tech_var': TRUE, 
    'type': 'non-negative reals', 
    'note': 'Implicitly, the model assumes that the unit is installed and operates for one year.', 
    'units': 'MW'},
    
    {'idx': 9006, 
    'year': 2020, 
    'storage_type': 'above', 
    'category': 'battery_storage', 
    'var_name': 'vStCharge', 
    'time_var': TRUE, 
    'tech_var': TRUE, 
    'type': 'non-negative reals', 
    'note': 'Implicitly, the model assumes that the unit is installed and operates for one year.', 
    'units': 'MW'},
    
    {'idx': 9007, 
    'year': 2020, 
    'storage_type': 'above', 
    'category': 'battery_storage', 
    'var_name': 'vStSoC', 
    'time_var': TRUE, 
    'tech_var': TRUE, 
    'type': 'non-negative reals', 
    'note': 'none'},
    
    {'idx': 9008, 
    'year': 2020, 
    'storage_type': 'above', 
    'category': 'battery_storage', 
    'var_name': 'vStInstalledMW', 
    'time_var': FALSE, 
    'tech_var': TRUE, 
    'type': 'non-negative reals', 
    'note': 'Implicitly, the model assumes that the unit is installed and operates for one year.', 
    'units': 'MW'},
    
    {'idx': 9009, 
    'year': 2020, 
    'storage_type': 'above', 
    'category': 'battery_storage', 
    'var_name': 'vStInstalledMWh', 
    'time_var': FALSE, 
    'tech_var': TRUE, 
    'type': 'non-negative reals', 
    'note': 'Implicitly, the model assumes that the unit is installed and operates for one year.',  
    'units': 'MW'},
    
    {'idx': 9010, 
    'year': 2020, 
    'storage_type': 'above', 
    'category': 'electrolyzer', 
    'var_name': 'vElyInstalledMW', 
    'time_var': FALSE, 
    'tech_var': FALSE, 
    'type': 'non-negative reals', 
    'note': 'Implicitly, the model assumes that the unit is installed and operates for one year.', 
    'units': 'MW'},
    
    {'idx': 9011, 
    'year': 2020, 
    'storage_type': 'above', 
    'category': 'electrolyzer', 
    'var_name': 'vDCPowtoEly', 
    'time_var': TRUE, 
    'tech_var': FALSE, 
    'type': 'non-negative reals', 
    'note': 'none'},
    
    {'idx': 9012, 
    'year': 2020, 
    'storage_type': 'above', 
    'category': 'hydrogen_storage_compressor', 
    'var_name': 'vCompInstalledMW', 
    'time_var': FALSE, 
    'tech_var': FALSE, 
    'type': 'non-negative reals', 
    'note': 'none'},
    
    {'idx': 9013, 
    'year': 2020, 
    'storage_type': 'above', 
    'category': 'hydrogen_storage_compressor', 
    'var_name': 'vH2StInstalledNumber', 
    'time_var': FALSE, 
    'tech_var': FALSE, 
    'type': 'non-negative reals', 
    'note': 'none', 
    'units': 'units'},
    
    {'idx': 9014, 
    'year': 2020, 
    'storage_type': 'above', 
    'category': 'hydrogen_storage_compressor', 
    'var_name': 'vH2flowProd', 
    'time_var': TRUE, 
    'tech_var': FALSE, 
    'type': 'non-negative reals', 
    'note': 'none', 
    'units': 'kg/hr'},
    
    {'idx': 9015,
    'year': 2020, 
    'storage_type': 'above', 
    'category': 'hydrogen_storage_compressor', 
    'var_name': 'vH2flowStorage', 
    'time_var': TRUE, 
    'tech_var': FALSE, 
    'type': 'non-negative reals', 
    'note': 'none', 
    'units': 'kg/hr'},
    
    {'idx': 9016, 
    'year': 2020, 
    'storage_type': 'above', 
    'category': 'hydrogen_storage_compressor', 
    'var_name': 'vDCPowtoInv', 
    'time_var': TRUE, 
    'tech_var': FALSE, 
    'type': 'non-negative reals', 
    'note': 'none'},

    {'idx': 9017, 
    'year': 2020, 
    'storage_type': 'above', 
    'category': 'hydrogen_storage_compressor', 
    'var_name': 'vACPowtoComp', 
    'time_var': TRUE, 
    'tech_var': FALSE, 
    'type': 'non-negative reals', 
    'note': 'none'},
    
    {'idx': 9018, 
    'year': 2020, 
    'storage_type': 'above', 
    'category': 'hydrogen_storage_compressor', 
    'var_name': 'vACPowtoGrid', 
    'time_var': TRUE, 
    'tech_var': FALSE, 
    'type': 'non-negative reals', 
    'note': 'This is the amount sent to the grid in one hour. Implicitly, the units are MW-hr.',
    'units': 'MW'},
    
    {'idx': 9019, 
    'year': 2020, 
    'storage_type': 'above', 
    'category': 'hydrogen_storage_compressor', 
    'var_name': 'vH2StStatekg', 
    'time_var': TRUE, 
    'tech_var': FALSE, 
    'type': 'non-negative reals', 
    'note': 'none'},

    {'idx': 9020, 
    'year': 2020, 
    'storage_type': 'above', 
    'category': 'hydrogen_storage_compressor', 
    'var_name': 'vH2StflowProd', 
    'time_var': TRUE, 
    'tech_var': FALSE, 
    'type': 'non-negative reals', 
    'note': 'none'},

    {'idx': 9021, 
    'year': 2020, 
    'storage_type': 'above', 
    'category': 'hydrogen_storage_compressor', 
    'var_name': 'vTotalH2Output', 
    'time_var': TRUE, 
    'tech_var': FALSE, 
    'type': 'non-negative reals', 
    'note': 'none'},
    
    {'idx': 9022, 
    'year': 2020, 
    'storage_type': 'above', 
    'category': 'hydrogen_storage_compressor', 
    'var_name': 'vH2PlantOutputSlack', 
    'time_var': TRUE, 
    'tech_var': FALSE, 
    'type': 'non-negative reals', 
    'note': 'initialized to zero', 
    'units': 'kg/hr'}
]
