parameterDict2020AG = [

    {'idx': 8001, 
    'year': 2020, 
    'storage_type': 'above', 
    'category': 'general', 
    'param_name': 'pCCF', 
    'value': 0.07873476636464005, 
    'comments': 'Calculated field using the discount rate (5.4 %) and lifetime value (20 years).'},

    {'idx': 8002, 
    'year': 2020, 
    'storage_type': 'above', 
    'category': 'hydrogen_production', 
    'param_name': 'pH2DesignFlowRate', 
    'value': 4166.667, 
    'comments': 'Assumption, fixed a priori'},
    
    {'idx': 8003, 
    'year': 2020, 
    'storage_type': 'above', 
    'category': 'hydrogen_production', 
    'param_name': 'pCFPlantLB', 
    'value': 0.9, 
    'comments': 'Lower bound on plant activity, fixed a priori.'},

    {'idx': 8004, 
    'year': 2020, 
    'storage_type': 'above', 
    'category': 'hydrogen_production', 
    'param_name': 'pH2LHV', 
    'value': 120.1, 
    'comments': 'Assumption, fixed a priori'},

    {'idx': 8005, 
    'year': 2020, 
    'storage_type': 
    'above', 'category': 'hydrogen_production', 
    'param_name': 'pProductionSlackCost', 
    'value': 0, 
    'comments': 'Initially fixed at zero before model runs.'},

    {'idx': 8006, 
    'year': 2020, 
    'storage_type': 'above', 
    'category': 'pv', 
    'param_name': 'pCapCostPV', 
    'value': 850.0, 
    'comments': 'NREL Q1 2018 benchmark $/kWdc https://www.nrel.gov/docs/fy19osti/72399.pdf'},

    {'idx': 8007, 
    'year': 2020, 
    'storage_type': 'above', 
    'category': 'pv', 
    'param_name': 'pFOMCostPV', 
    'value': 8500.0, 
    'comments': 'Assumed to be 1% of CAPEX `pCapCostPV` and converted to $/MW.'},

    {'idx': 8008, 
    'year': 2020, 
    'storage_type': 'above', 
    'category': 'pv', 
    'param_name': 'pVOMCostPV', 
    'value': 0.0, 
    'comments': 'Assumption, fixed a priori'},

    {'idx': 8009, 
    'year': 2020, 
    'storage_type': 'above', 
    'category': 'pv', 
    'param_name': 'pPVCapFactor', 
    'value': None, 
    'comments': 'From external data source (NREL, TMY), for each site in the model.'},

    {'idx': 8010, 
    'year': 2020, 
    'storage_type': 'above', 
    'category': 'pv', 
    'param_name': 'pGridElecPrice', 
    'value': 120.0, 'comments': 'Fixed, a priori'},

    {'idx': 8011, 
    'year': 2020, 
    'storage_type': 'above', 
    'category': 'inverter', 
    'param_name': 'pCapCostInv', 
    'value': 60.0, 
    'comments': 'Assumption made by Mallagragada et al.'},

    {'idx': 8012, 
    'year': 2020, 
    'storage_type': 'above', 
    'category': 'inverter', 
    'param_name': 'pInvEff', 
    'value': 0.96, 
    'comments': 'Assumption, fixed a priori'},

    {'idx': 8013, 
    'year': 2020, 
    'storage_type': 'above', 
    'category': 'battery_storage', 
    'param_name': 'pStEffChg', 
    'value': 0.96, 
    'comments': 'Assumption, fixed a priori'},

    {'idx': 8014, 
    'year': 2020, 
    'storage_type': 'above', 
    'category': 'battery_storage', 
    'param_name': 'pStEffDischg',  
    'value': 0.96, 'comments': 'Assumption, fixed a priori'},

    {'idx': 8015, 
    'year': 2020, 
    'storage_type': 'above', 
    'category': 'battery_storage', 
    'param_name': 'pCapCostPowSt', 
    'value': 589.0, 'comments': 'Assumption, fixed a priori (ref. 13)'},

    {'idx': 8016, 
    'year': 2020, 
    'storage_type': 'above', 
    'category': 'battery_storage', 
    'param_name': 'pCapCostEnergySt', 
    'value': 206.0, 
    'comments': 'Assumption, fixed a priori (ref. 13)'},

    {'idx': 8017, 
    'year': 2020, 
    'storage_type': 'above', 
    'category': 'battery_storage', 
    'param_name': 'pFOMCostSt', 
    'value': 7873.0, 
    'comments': 'NREL ATB 2018 2020 costs (need to get full reference).'},

    {'idx': 8018, 
    'year': 2020, 
    'storage_type': 'above', 
    'category': 'battery_storage', 
    'param_name': 'pVOMCostSt', 
    'value': 2.7, 
    'comments': 'Assumption, fixed a priori'},

    {'idx': 8019, 
    'year': 2020, 
    'storage_type': 'above', 
    'category': 'battery_storage', 
    'param_name': 'pDur_UB', 
    'value': 100.0, 
    'comments': 'Assumption, fixed a priori'},
    
    {'idx': 8020, 
    'year': 2020, 
    'storage_type': 'above', 
    'category': 'electrolyzer', 
    'param_name': 'pElySpecPower',  
    'value': 57.51915709, 
    'comments': 'Median value for electrolyzer efficiency from IEA Future of Hydrogen report, 2019 (=1/0.58*120.1/3.6)'},
    
    {'idx': 8021, 
    'year': 2020, 
    'storage_type': 'above', 
    'category': 'electrolyzer', 
    'param_name': 'pCapCostEly', 
    'value': 800.0, 
    'comments': 'Value is from Table 2 in `https://www.nrel.gov/docs/fy16osti/65856.pdf`'},
    
    {'idx': 8022, 
    'year': 2020, 
    'storage_type': 'above', 
    'category': 'electrolyzer', 
    'param_name': 'pVOMCostEly', 
    'value': 0.00, 
    'comments': 'Assumption, fixed a priori'},
    
    {'idx': 8023, 
    'year': 2020, 
    'storage_type': 'above', 
    'category': 'electrolyzer', 
    'param_name': 'pFOMCostEly', 
    'value': 56000.0, 
    'comments': 'Assumed to be 7% of CAPEX `pCapCostEly` and converted to $/MW.'},
    
    {'idx': 8024, 
    'year': 2020, 
    'storage_type': 'above', 
    'category': 'electrolyzer', 
    'param_name': 'pFeedH2OCostEly', 
    'value': 0.014867499, 
    'comments': 'Value is from Table 10 in `https://www.nrel.gov/docs/fy17osti/67384.pdf` (=0.002375*(2.36+3.9)'},
    
    {'idx': 8025, 
    'year': 2020, 
    'storage_type': 'above', 
    'category': 'hydrogen_storage_compressor', 
    'param_name': 'pCapCostH2Comp', 
    'value': 1200.0, 'comments': 'Comes from `CapCostComp_dkW` (Parks et al, ref 61).'},
    
    {'idx': 8026, 
    'year': 2020, 
    'storage_type': 'above', 
    'category': 'hydrogen_storage_compressor', 
    'param_name': 'pFOMCostH2Comp', 
    'value': 48000.0, 
    'comments': 'Assumed to be 1% of CAPEX `pCapCostH2Comp` and converted to $/MW.'},
    
    {'idx': 8027, 
    'year': 2020, 
    'storage_type': 'above', 
    'category': 'hydrogen_storage_compressor', 
    'param_name': 'pCompSpecPower', 
    'value': 1.0, 
    'comments': 'Assumption made by Mallagragada et al. based on a book (Need to get full reference).'},
    
    {'idx': 8028, 
    'year': 2020, 
    'storage_type': 'above', 
    'category': 'hydrogen_storage_compressor', 
    'param_name': 'pCapCostH2st', 
    'value': 516.0, 
    'comments': 'Fixed a priori from Ahluwalia et al. (Need to get full reference).'},
    
    {'idx': 8029, 
    'year': 2020, 
    'storage_type': 'above', 
    'category': 'hydrogen_storage_compressor', 
    'param_name': 'pFOMCostH2st', 
    'value': 5.16, 'comments': 'Assumed to be 1% from CAPEX `pCapCostH2st` (Penev et al, ref 62).'},
    
    {'idx': 8030, 
    'year': 2020, 
    'storage_type': 'above', 
    'category': 'hydrogen_storage_compressor', 
    'param_name': 'pH2kgpertank', 
    'value': 1000.0, 
    'comments': 'Assumption, fixed a priori'}
]
